# Generated by Django 4.2 on 2023-05-16 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='usermodel',
            name='dob',
            field=models.DateField(default='2022-02-02'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermodel',
            name='pincode',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='address',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='otp',
            field=models.IntegerField(default='654564'),
            preserve_default=False,
        ),
    ]
